var count3 = 1;
var count2 = 1;
var countMain = 1;
d3.selectAll("#TestGrid").style("display","none")
d3.selectAll("#Test3D").style("display","none")

var main = d3.selectAll("#MainGUI")
            .append("div")
            .attr("id","GUIMainWrap")
            .style("display","flex")
            .attr("height","50px")
            .style("background-color","rgb("+colorGUIBackground+")")
            .style("padding","5px")
            .style("flex-wrap","wrap")
            .style("flex-shrink","0")
            .style("align-items","center")
            .style("align-content","center")
            .style("justify-content","center")
            .style("border-bottom-style","solid")
            .style("border-width","0.5px")
            .style("border-color","rgb("+colorButtonsHover+")")
            .style("border-radius","50px")
            .style("z-index","99")
            .style("width","720px")
            .append("div")
            .attr("id","CanvasButtons")
            .attr("style","ButtonsGlobal")
            

main.append("button").attr("class","MB threedim").append("span").attr("class","material-symbols-outlined").text("deployed_code")
main.append("button").attr("class","MB twodim").append("span").attr("class","material-symbols-outlined").text("grid_view")
main.append("button").attr("class","MB maindim").append("span").attr("class","material-symbols-outlined").text("lens_blur")
var main = d3.selectAll("#GUIMainWrap")
main.append("div").attr("id","MB essentials").attr("class","gui system")

for (var i = 0; i < 3; i++){
    main.append("div").attr("class","gui" + i + " system").attr("id","ModelGui " + i + "system")
            .attr("width","auto")
            .attr("height","auto")
            .style("position","relative")
            .style("display","flex")
            .style("padding","3px")
            .style("gap","10px")
            .style("background-color","rgb("+colorGUIBackground+")")

}

var buttons = d3.select("body").selectAll("button")
    buttons.style("background-color","rgb("+colorButtons+")")
            .style("display","flex")
            .style("padding","3px")
            .style("gap","3px")
            .style("align-items","center")
            .style("color","white")
            .style("border-style","none")
            .style("border-bottom-style","solid")
            .style("border-width","0.5px")
            .style("border-radius","5px")
            .style("border-color","rgb("+colorButtonsHover+")")
            .style("padding","10px")
            .style("margin-left","10px")
            
var modelgui = d3.selectAll(".ModelGui")

d3.selectAll(".threedim").on("click",function(){
    d3.selectAll(".system").style("display","none")
    d3.selectAll(".gui").style("display","flex")
    d3.selectAll(".gui2").style("display","flex")
    d3.selectAll("#Test3D").style("display","flex")
    d3.selectAll("#Test").style("display","none")
    d3.selectAll("#TestGrid").style("display","none")
    d3.selectAll("#TestGUI").style("display","none")
    d3.selectAll("#TestGUIRight").style("display","none")

    d3.selectAll("button").style("background-color","rgb("+colorButtons+")")
    d3.selectAll(".threedim").style("background-color","rgb("+colorButtonsSelected+")")
    d3.selectAll("#GUIMainWrap").style("width","auto")
})
d3.selectAll(".twodim").on("click",function(){
    d3.selectAll(".system").style("display","none")
    d3.selectAll(".gui").style("display","flex")
    d3.selectAll(".gui1").style("display","flex")
        d3.selectAll("#TestGrid").style("display","flex")
        d3.selectAll("#Test").style("display","none")
        d3.selectAll("#TestGUI").style("display","none")
        d3.selectAll("#Test3D").style("display","none")
        d3.selectAll("#TestGUIRight").style("display","none")

    d3.selectAll("button").style("background-color","rgb("+colorButtons+")")
    d3.selectAll(".twodim").style("background-color","rgb("+colorButtonsSelected+")")
    d3.selectAll("#GUIMainWrap").style("width","auto")
})
d3.selectAll(".maindim").on("click",function(){
    d3.selectAll(".system").style("display","none")
    d3.selectAll(".gui").style("display","flex")
    d3.selectAll(".gui0").style("display","flex")
        d3.selectAll("#TestGrid").style("display","none")
        d3.selectAll("#Test3D").style("display","none")
        d3.selectAll("#Test").style("display","flex")
        d3.selectAll("#TestGUI").style("display","flex")
        d3.selectAll("#TestGUIRight").style("display","flex")
        d3.selectAll("#GUIMainWrap").style("width","720px")

        d3.selectAll("button").style("background-color","rgb("+colorButtons+")")
    d3.selectAll(".maindim").style("background-color","rgb("+colorButtonsSelected+")")
})

d3.selectAll(".system").style("display","none")
    d3.selectAll(".gui").style("display","flex")
    d3.selectAll(".gui0").style("display","flex")
        d3.selectAll("#TestGrid").style("display","none")
        d3.selectAll("#Test3D").style("display","none")
        d3.selectAll("#Test").style("display","flex")
        d3.selectAll("#TestGUI").style("display","flex")
        d3.selectAll("#TestGUIRight").style("display","flex")
        d3.selectAll("#GUIMainWrap").style("width","720px")

        d3.selectAll("button").style("background-color","rgb("+colorButtons+")")
    d3.selectAll(".maindim").style("background-color","rgb("+colorButtonsSelected+")")